<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <Target Name="BuildFrontend" BeforeTargets="BeforeBuild">
    <Exec Command="npm run build" WorkingDirectory="$(ProjectDir)" />
  </Target>

  <ItemGroup>
    <Content Include="./dist/**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
